del /s D:\MyProjects\MagicPanel\make_manual\*.aux
del /s D:\MyProjects\MagicPanel\make_manual\*.bbl
del /s D:\MyProjects\MagicPanel\make_manual\*.bcf
del /s D:\MyProjects\MagicPanel\make_manual\*.blg
del /s D:\MyProjects\MagicPanel\make_manual\*.log
del /s D:\MyProjects\MagicPanel\make_manual\*.nav
del /s D:\MyProjects\MagicPanel\make_manual\*.out
del /s D:\MyProjects\MagicPanel\make_manual\*.run.xml
del /s D:\MyProjects\MagicPanel\make_manual\*.snm
del /s D:\MyProjects\MagicPanel\make_manual\*.synctex.gz
del /s D:\MyProjects\MagicPanel\make_manual\*.toc
del /s D:\MyProjects\MagicPanel\make_manual\*.vrb
